### ISSUE TITLE
Choose license for define

### ISSUE THREAD

**Issue by shymega** [vktec-irc/define#1]
We should choose a license for define's code.

I'm not sure what CHICKEN Scheme's licensing conventions are - do they
use GPLv2,3 a lot? MIT?

Guile (More familiar with Guile, personally) seems to use GPLv2,3 in
the ecosystem.

I'd be inclined to suggest GPLv3 for define, but @vktec - as you're
the creator, it's ultimately up to you, as long as it's discussed.

I'd recommend that we make clear that all contributors agree to the
licensing change.

Currently this repo has defaulted to `All Rights Reserved` to @vktec.

**Comment by vktec** [comment]
CHICKEN and most programs written in it use the BSD 3-clause license,
but I don't think using MIT or GPL would be an issue, since we're not
distributing CHICKEN itself, only using it and its libraries.

I agree that GPLv3 would be a good choice, but I'm open to other suggestions.

**Comment by shymega** [comment]
I agree as well that GPLv3 would be a good choice.

Perhaps we could apply that soon-ish. Would you like me to apply it to
this repo via a PR or directly?

**Comment by vktec** [comment]
I'd say just make a `license` branch and stick the relevant bits in the relevant files, then merge that. There shouldn't be any merge conflicts and people have had _plenty_ of time to object to this.

**Comment by shymega** [comment]
Hello,

Samadi van Koten <notifications@github.com> writes:

> I'd say just make a `license` branch and stick the relevant bits in
> the relevant files, then merge that.

Done that.
See commit "125fc6105165f1c06293994ea1f0690ebf81bf4b" on branch
"license".

> There shouldn't be any merge conflicts and people have had _plenty_
> of time to object to this.

No, there should not be any merge conflicts.

And yes, people have had time to object.

Waiting for the all-clear to merge into master.

-- 
Best regards,
Dom Rodriguez

**Comment by vktec** [comment]
Looks good to me, go for it!

**Comment by shymega** [comment]
Hello,

Samadi van Koten <notifications@github.com> writes:

> Looks good to me, go for it!

Merged. Waiting for my hourly cronjob to push the repo over :-)

-- 
Best regards,
Dom Rodriguez

**Comment by vktec** [comment]
Great! Thanks for catching this, by the way, I nearly always forget to license stuff :P

**Comment by shymega** [comment]
Hello,

Samadi van Koten <notifications@github.com> writes:

> Great! Thanks for catching this, by the way

No problem.

..I guess I have a "keen" eye for licensing.. but free/libre software
licenses only of course - not that non-free cr*p..

> ,I nearly always forget to license stuff :P

Yes. Quite a lot of your projects are *not* licensed, and need
rectifying.

-- 
Best regards,
Dom Rodriguez
